//! Build script: generate an embedded manifest of every campaign/scenario JSON.
//!
//! Base-game content used to be pulled in with a single hardcoded `include_str!`
//! per loader (one campaign, one scenario), so adding a mission meant editing
//! Rust. Instead we scan `assets/campaigns/` and `assets/scenarios/` here at
//! build time and emit `include_str!`-backed arrays. The result:
//!   - WASM builds get every file embedded automatically (the "WASM embedded
//!     manifest") — add a file, rebuild, it ships.
//!   - Native builds additionally re-scan the directory at runtime (see
//!     `data::content_source`), so a dropped-in mission loads with no rebuild.
//!
//! Either way, authoring a mission is pure content work — no code changes.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");

    let mut generated = String::from("// @generated by build.rs — do not edit.\n\n");
    emit_dir(
        &mut generated,
        &manifest_dir,
        "assets/campaigns",
        "EMBEDDED_CAMPAIGNS",
    );
    emit_dir(
        &mut generated,
        &manifest_dir,
        "assets/scenarios",
        "EMBEDDED_SCENARIOS",
    );

    let dest = Path::new(&out_dir).join("embedded_content.rs");
    fs::write(&dest, generated).expect("write embedded_content.rs");
}

/// Emit `pub static <const_name>: &[&str] = &[ include_str!(...), ... ];` for
/// every `*.json` in `<manifest_dir>/<rel>`, sorted for deterministic output.
fn emit_dir(out: &mut String, manifest_dir: &str, rel: &str, const_name: &str) {
    let dir = Path::new(manifest_dir).join(rel);
    // Re-run whenever the directory itself changes (files added/removed)...
    println!("cargo:rerun-if-changed={}", dir.display());

    let mut json_files: Vec<PathBuf> = fs::read_dir(&dir)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", dir.display()))
        .filter_map(|entry| entry.ok().map(|e| e.path()))
        .filter(|path| path.extension().and_then(|x| x.to_str()) == Some("json"))
        .collect();
    json_files.sort();

    out.push_str(&format!("pub static {const_name}: &[&str] = &[\n"));
    for path in &json_files {
        // ...and whenever any embedded file's contents change.
        println!("cargo:rerun-if-changed={}", path.display());
        // include_str! accepts forward slashes on every platform.
        let literal = path.to_string_lossy().replace('\\', "/");
        out.push_str(&format!("    include_str!(\"{literal}\"),\n"));
    }
    out.push_str("];\n\n");
}
